### PR TITLE
abundance GAMs

### PR DESCRIPTION
**Pull request by davharris**
The first part of the code is basically copy-pasted from yours, except for the if statement on line 155.  Without it, I got errors outside of the 1995-2010 time frame because of period/plot combinations that never occurred.  R got unhappy about vectors of length 0, I think.

I thought I'd mention it just in case my if statement doesn't perform the correct behavior.

Also, when I go outside the 1995-2010 time frame, the nightlyLookupTable seems to take _much_ longer to build (much more than the 3x or 4x slowdown that I'd expected).  I'm not sure what it's doing, but it might be worth looking into.  I don't fully understand that section of the code, so I won't muck around with it, but I thought I should mention the issue.  It might not even be necessary for the kind of analysis I'm doing, but I'm not sure.

Thanks again for your data cleanup!

### CODE REVIEW

**Comment by davharris** [comment]
I mean, thanks again for _sharing_ your data cleanup code.

**Comment by sdtaylor** [comment]
My pleasure! I'll look into the lookup table stuff.

**Comment by sdtaylor** [comment]
Just took a quick look at the GAM model. You could probably include it by putting in  0 abundances for the rodents.

**Comment by davharris** [comment]
Oh, duh.  Excellent point!

**Pull request merged**
